name: sharing_into_flutter_app
description: A new Flutter project.

version: 1.1.1+21

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  share_handler: ^0.0.16

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "logo.png"
